# 开发环境配置
ip: 127.0.0.1
# 端口
server:
  port: 8888

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://47.97.80.123:3306/warmwind-master?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: warmwind666centos
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# docs配置
springdoc:
  api-docs:
    enabled: true
    path: /warmwind/v3/api-docs
  swagger-ui:
    enabled: true
    path: /warmwind/swagger-ui/index.html

# 日志配置
logging:
  level:
    top.warmwind.master: DEBUG
    com.baomidou.mybatisplus: DEBUG
    root: INFO
  pattern:
    console: "%red(%d{HH:mm:ss.SSS})|%green(%level)|%magenta(%thread)|%yellow(%logger{32})|%green(line-%line)|%cyan(%X{traceId})|%m%n"

# minio配置
minio:
  endpoint: http://${ip}:9000
  accessKey: warmwind
  secretKey: warmwind623
  suffixs: .jpg,.png,.jpeg
  expiry: 600