# dev
# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://47.97.80.123:3306/warmwind?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Qq2693387413@
    driver-class-name: com.mysql.cj.jdbc.Driver