# 开发环境配置

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://47.97.80.123:3306/alumni-association?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Qq2693387413@
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# 日志配置
logging:
  level:
    top.warmwind.master: DEBUG
    com.baomidou.mybatisplus: DEBUG
    root: INFO
  pattern:
    console: "%red(%d{HH:mm:ss.SSS})|%green(%level)|%magenta(%thread)|%yellow(%logger{32})|%green(line-%line)|%cyan(%X{traceId})|%m%n"